vim.cmd("highlight clear")
vim.g.colors_name = "matrix"
vim.o.background = "dark"

local c = {
	none = "NONE",
	black = "#000000",
	bg1 = "#011508",
	bg2 = "#03240d",
	bg3 = "#063d16",
	dim = "#0b6b26",
	mid = "#159a38",
	fg = "#20c84a",
	bright = "#00ff41",
	lime = "#4dff88",
	pale = "#7dffa0",
	mint = "#c0ffd0",
	white = "#e0ffe8",
	text = "#d0d8d0",
	grey = "#6e7681",
	punct = "#8b949e",
	blue = "#61afef",
	sky = "#9cdcfe",
	cyan = "#56d4dd",
	yellow = "#e6db74",
	purple = "#c792ea",
	magenta = "#ff79c6",
	orange = "#ffa066",
	red = "#ff3b3b",
	amber = "#ffb000",
	red_bg = "#2a0505",
	amber_bg = "#2a1d00",
	green_bg = "#022a0e",
}

local hl = {
	Normal = { fg = c.text, bg = c.none },
	NormalNC = { fg = c.text, bg = c.none },
	NormalFloat = { fg = c.text, bg = c.black },
	FloatBorder = { fg = c.mid, bg = c.black },
	FloatTitle = { fg = c.bright, bg = c.black, bold = true },
	FloatFooter = { fg = c.mid, bg = c.black },
	EndOfBuffer = { fg = c.bg3, bg = c.none },
	NonText = { fg = c.bg3 },
	Whitespace = { fg = c.bg3 },
	SpecialKey = { fg = c.dim },
	Conceal = { fg = c.dim },

	Cursor = { fg = c.black, bg = c.bright },
	lCursor = { link = "Cursor" },
	CursorIM = { link = "Cursor" },
	TermCursor = { link = "Cursor" },
	CursorLine = { bg = c.bg1 },
	CursorColumn = { bg = c.bg1 },
	ColorColumn = { bg = c.bg1 },
	CursorLineNr = { fg = c.bright, bold = true },
	LineNr = { fg = c.dim, bg = c.none },
	LineNrAbove = { link = "LineNr" },
	LineNrBelow = { link = "LineNr" },
	SignColumn = { fg = c.dim, bg = c.none },
	FoldColumn = { fg = c.dim, bg = c.none },
	Folded = { fg = c.mid, bg = c.bg1, italic = true },
	VertSplit = { fg = c.bg3 },
	WinSeparator = { fg = c.bg3 },

	StatusLine = { fg = c.fg, bg = c.bg1 },
	StatusLineNC = { fg = c.dim, bg = c.none },
	TabLine = { fg = c.dim, bg = c.bg1 },
	TabLineFill = { bg = c.none },
	TabLineSel = { fg = c.black, bg = c.bright, bold = true },
	WinBar = { fg = c.fg, bold = true },
	WinBarNC = { fg = c.dim },

	Visual = { bg = c.bg3 },
	VisualNOS = { bg = c.bg3 },
	Search = { fg = c.black, bg = c.pale },
	IncSearch = { fg = c.black, bg = c.bright, bold = true },
	CurSearch = { link = "IncSearch" },
	Substitute = { fg = c.black, bg = c.amber },
	MatchParen = { fg = c.white, bg = c.bg3, bold = true },
	QuickFixLine = { bg = c.bg2, bold = true },

	Pmenu = { fg = c.text, bg = c.bg1 },
	PmenuSel = { fg = c.black, bg = c.fg, bold = true },
	PmenuSbar = { bg = c.bg2 },
	PmenuThumb = { bg = c.mid },
	PmenuKind = { fg = c.pale, bg = c.bg1 },
	PmenuExtra = { fg = c.dim, bg = c.bg1 },
	WildMenu = { link = "PmenuSel" },

	ModeMsg = { fg = c.bright, bold = true },
	MoreMsg = { fg = c.bright },
	MsgArea = { fg = c.text },
	Question = { fg = c.pale },
	Title = { fg = c.bright, bold = true },
	Directory = { fg = c.pale },
	ErrorMsg = { fg = c.red, bold = true },
	WarningMsg = { fg = c.amber },
	SpellBad = { undercurl = true, sp = c.red },
	SpellCap = { undercurl = true, sp = c.amber },
	SpellLocal = { undercurl = true, sp = c.mid },
	SpellRare = { undercurl = true, sp = c.mid },

	Comment = { fg = c.grey, italic = true },
	Constant = { fg = c.purple },
	String = { fg = c.yellow },
	Character = { fg = c.orange },
	Number = { fg = c.purple },
	Boolean = { fg = c.purple, bold = true },
	Float = { link = "Number" },
	Identifier = { fg = c.text },
	Function = { fg = c.blue },
	Statement = { fg = c.bright, bold = true },
	Conditional = { link = "Statement" },
	Repeat = { link = "Statement" },
	Label = { fg = c.orange },
	Operator = { fg = c.punct },
	Keyword = { link = "Statement" },
	Exception = { link = "Statement" },
	PreProc = { fg = c.magenta },
	Include = { link = "PreProc" },
	Define = { link = "PreProc" },
	Macro = { fg = c.magenta, italic = true },
	PreCondit = { link = "PreProc" },
	Type = { fg = c.cyan },
	StorageClass = { fg = c.bright },
	Structure = { link = "Type" },
	Typedef = { link = "Type" },
	Special = { fg = c.orange },
	SpecialChar = { fg = c.orange },
	Tag = { fg = c.blue },
	Delimiter = { fg = c.punct },
	SpecialComment = { fg = c.grey, italic = true, bold = true },
	Debug = { fg = c.amber },
	Underlined = { underline = true },
	Ignore = { fg = c.bg3 },
	Error = { fg = c.red, bold = true },
	Todo = { fg = c.black, bg = c.amber, bold = true },
	Added = { fg = c.bright },
	Changed = { fg = c.amber },
	Removed = { fg = c.red },

	["@variable"] = { fg = c.text },
	["@variable.builtin"] = { fg = c.red, italic = true },
	["@variable.parameter"] = { fg = c.text, italic = true },
	["@variable.member"] = { fg = c.sky },
	["@property"] = { fg = c.sky },
	["@constant"] = { link = "Constant" },
	["@constant.builtin"] = { fg = c.purple, bold = true },
	["@constant.macro"] = { link = "Macro" },
	["@module"] = { fg = c.cyan, italic = true },
	["@label"] = { link = "Label" },
	["@string"] = { link = "String" },
	["@string.escape"] = { fg = c.orange, bold = true },
	["@string.special"] = { fg = c.orange },
	["@character"] = { link = "Character" },
	["@number"] = { link = "Number" },
	["@boolean"] = { link = "Boolean" },
	["@function"] = { link = "Function" },
	["@function.builtin"] = { fg = c.blue, italic = true },
	["@function.macro"] = { link = "Macro" },
	["@constructor"] = { fg = c.cyan },
	["@operator"] = { link = "Operator" },
	["@keyword"] = { link = "Keyword" },
	["@keyword.directive"] = { link = "PreProc" },
	["@keyword.import"] = { link = "Include" },
	["@type"] = { link = "Type" },
	["@type.builtin"] = { fg = c.cyan, italic = true },
	["@attribute"] = { fg = c.orange, italic = true },
	["@punctuation"] = { link = "Delimiter" },
	["@punctuation.bracket"] = { fg = c.punct },
	["@punctuation.delimiter"] = { fg = c.punct },
	["@punctuation.special"] = { fg = c.orange },
	["@comment"] = { link = "Comment" },
	["@comment.todo"] = { link = "Todo" },
	["@comment.note"] = { fg = c.black, bg = c.pale, bold = true },
	["@comment.warning"] = { fg = c.black, bg = c.amber, bold = true },
	["@comment.error"] = { fg = c.black, bg = c.red, bold = true },
	["@tag"] = { link = "Tag" },
	["@tag.attribute"] = { fg = c.sky, italic = true },
	["@tag.delimiter"] = { fg = c.punct },
	["@markup.heading"] = { fg = c.bright, bold = true },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.underline"] = { underline = true },
	["@markup.raw"] = { fg = c.yellow },
	["@markup.link"] = { fg = c.blue, underline = true },
	["@markup.link.url"] = { fg = c.sky, underline = true },
	["@markup.list"] = { fg = c.bright },
	["@markup.quote"] = { fg = c.grey, italic = true },
	["@diff.plus"] = { link = "Added" },
	["@diff.minus"] = { link = "Removed" },
	["@diff.delta"] = { link = "Changed" },

	["@lsp.type.namespace"] = { link = "@module" },
	["@lsp.type.parameter"] = { link = "@variable.parameter" },
	["@lsp.type.property"] = { link = "@property" },
	["@lsp.type.macro"] = { link = "Macro" },
	["@lsp.mod.deprecated"] = { strikethrough = true },
	LspReferenceText = { bg = c.bg2 },
	LspReferenceRead = { bg = c.bg2 },
	LspReferenceWrite = { bg = c.bg2, underline = true },
	LspInlayHint = { fg = c.grey, italic = true },
	LspSignatureActiveParameter = { fg = c.bright, bold = true, underline = true },
	LspCodeLens = { fg = c.dim },

	DiagnosticError = { fg = c.red },
	DiagnosticWarn = { fg = c.amber },
	DiagnosticInfo = { fg = c.pale },
	DiagnosticHint = { fg = c.mid },
	DiagnosticOk = { fg = c.bright },
	DiagnosticUnderlineError = { undercurl = true, sp = c.red },
	DiagnosticUnderlineWarn = { undercurl = true, sp = c.amber },
	DiagnosticUnderlineInfo = { undercurl = true, sp = c.pale },
	DiagnosticUnderlineHint = { undercurl = true, sp = c.mid },
	DiagnosticVirtualTextError = { fg = c.red, bg = c.red_bg, italic = true },
	DiagnosticVirtualTextWarn = { fg = c.amber, bg = c.amber_bg, italic = true },
	DiagnosticVirtualTextInfo = { fg = c.pale, bg = c.bg1, italic = true },
	DiagnosticVirtualTextHint = { fg = c.mid, bg = c.bg1, italic = true },
	DiagnosticUnnecessary = { fg = c.grey },
	DiagnosticDeprecated = { strikethrough = true },

	DiffAdd = { bg = c.green_bg },
	DiffChange = { bg = c.amber_bg },
	DiffDelete = { fg = c.red, bg = c.red_bg },
	DiffText = { bg = "#4a3300", bold = true },
	diffAdded = { link = "Added" },
	diffRemoved = { link = "Removed" },
	diffChanged = { link = "Changed" },

	GitSignsAdd = { fg = c.bright },
	GitSignsChange = { fg = c.amber },
	GitSignsDelete = { fg = c.red },
	GitSignsChangedelete = { fg = c.amber },
	GitSignsTopdelete = { fg = c.red },

	TelescopeNormal = { link = "NormalFloat" },
	TelescopeBorder = { link = "FloatBorder" },
	TelescopeTitle = { fg = c.black, bg = c.bright, bold = true },
	TelescopePromptPrefix = { fg = c.bright },
	TelescopePromptCounter = { fg = c.dim },
	TelescopeSelection = { fg = c.bright, bg = c.bg2, bold = true },
	TelescopeSelectionCaret = { fg = c.bright, bg = c.bg2 },
	TelescopeMultiSelection = { fg = c.pale },
	TelescopeMatching = { fg = c.white, bold = true },

	WhichKey = { fg = c.bright, bold = true },
	WhichKeyGroup = { fg = c.pale },
	WhichKeyDesc = { fg = c.fg },
	WhichKeySeparator = { fg = c.dim },
	WhichKeyValue = { fg = c.dim },
	WhichKeyNormal = { link = "NormalFloat" },
	WhichKeyBorder = { link = "FloatBorder" },

	BlinkCmpMenu = { link = "Pmenu" },
	BlinkCmpMenuBorder = { fg = c.mid, bg = c.bg1 },
	BlinkCmpMenuSelection = { link = "PmenuSel" },
	BlinkCmpLabelMatch = { fg = c.white, bold = true },
	BlinkCmpLabelDeprecated = { fg = c.dim, strikethrough = true },
	BlinkCmpKind = { fg = c.pale },
	BlinkCmpSource = { fg = c.dim },
	BlinkCmpGhostText = { fg = c.dim, italic = true },
	BlinkCmpDoc = { link = "NormalFloat" },
	BlinkCmpDocBorder = { link = "FloatBorder" },
	BlinkCmpSignatureHelp = { link = "NormalFloat" },
	BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },

	DapBreakpoint = { fg = c.red },
	DapStopped = { fg = c.amber },
	DapStoppedLine = { bg = c.amber_bg },
	NvimDapVirtualText = { fg = c.grey, italic = true },
	DapUIScope = { fg = c.bright, bold = true },
	DapUIType = { link = "Type" },
	DapUIValue = { fg = c.text },
	DapUIVariable = { fg = c.text },
	DapUIModifiedValue = { fg = c.amber, bold = true },
	DapUIDecoration = { fg = c.mid },
	DapUIThread = { fg = c.bright },
	DapUIStoppedThread = { fg = c.amber },
	DapUISource = { fg = c.pale },
	DapUILineNumber = { fg = c.mid },
	DapUIFloatBorder = { link = "FloatBorder" },
	DapUIWatchesEmpty = { fg = c.red },
	DapUIWatchesValue = { fg = c.bright },
	DapUIWatchesError = { fg = c.red },
	DapUIBreakpointsPath = { fg = c.pale },
	DapUIBreakpointsInfo = { fg = c.bright },
	DapUIBreakpointsCurrentLine = { fg = c.bright, bold = true },
	DapUIBreakpointsDisabledLine = { fg = c.dim },
	DapUIPlayPause = { fg = c.bright },
	DapUIRestart = { fg = c.bright },
	DapUIStop = { fg = c.red },
	DapUIStepOver = { fg = c.pale },
	DapUIStepInto = { fg = c.pale },
	DapUIStepBack = { fg = c.pale },
	DapUIStepOut = { fg = c.pale },
	DapUIUnavailable = { fg = c.dim },

	TodoBgTODO = { fg = c.black, bg = c.pale, bold = true },
	TodoFgTODO = { fg = c.pale },
	TodoBgFIX = { fg = c.black, bg = c.red, bold = true },
	TodoFgFIX = { fg = c.red },
	TodoBgWARN = { fg = c.black, bg = c.amber, bold = true },
	TodoFgWARN = { fg = c.amber },
	TodoBgHACK = { fg = c.black, bg = c.amber, bold = true },
	TodoFgHACK = { fg = c.amber },
	TodoBgNOTE = { fg = c.black, bg = c.bright, bold = true },
	TodoFgNOTE = { fg = c.bright },
	TodoBgPERF = { fg = c.black, bg = c.mint, bold = true },
	TodoFgPERF = { fg = c.mint },
	TodoBgTEST = { fg = c.black, bg = c.lime, bold = true },
	TodoFgTEST = { fg = c.lime },

	MiniSurround = { link = "IncSearch" },

	LazyNormal = { link = "NormalFloat" },
	LazyH1 = { fg = c.black, bg = c.bright, bold = true },
	LazyButton = { fg = c.fg, bg = c.bg2 },
	LazyButtonActive = { fg = c.black, bg = c.bright, bold = true },
	LazySpecial = { fg = c.bright },
	MasonNormal = { link = "NormalFloat" },
	MasonHeader = { fg = c.black, bg = c.bright, bold = true },
	MasonHighlight = { fg = c.bright },
	MasonHighlightBlockBold = { fg = c.black, bg = c.bright, bold = true },
	MasonMuted = { fg = c.dim },
}

for group, spec in pairs(hl) do
	vim.api.nvim_set_hl(0, group, spec)
end

local term = {
	c.black, c.red, c.fg, c.amber, c.blue, c.purple, c.cyan, c.text,
	c.grey, c.red, c.bright, c.yellow, c.sky, c.magenta, c.cyan, c.white,
}
for i, color in ipairs(term) do
	vim.g["terminal_color_" .. (i - 1)] = color
end
